# travis.yml

cache:
    directories:
        - $HOME/.composer/cache/files

language: php

php:
    - '7.0'

install:
 - composer update

script:
 - composer test

after_script:
- .build/bin/codacycoverage clover .build/clover.xml
